services:
  infra:
    build:
      context: .
    cap_add:
      - NET_ADMIN
    command:
      - bats
      - ${TEST_TARGET:-/tests}
    environment:
      BATS_TEST_TIMEOUT: "300"
    devices:
      - /dev/net/tun
      - /dev/kvm
    init: true
    restart: always
    volumes:
      - ./scripts:/scripts
      - ./boot:/boot
      - ./tests:/tests
      - ./results:/results
