services:
  infra:
    build:
      context: .
    cap_add:
      - NET_ADMIN
    command:
      - bats
      - /tests
    environment:
      BATS_TEST_TIMEOUT: "30"
    devices:
      - /dev/net/tun
      - /dev/kvm
    init: true
    restart: always
    volumes:
      - ./scripts:/scripts
      - ./boot:/boot
      - ./tests:/tests
      - results:/results
      - state:/state
volumes:
  results: {}
  state: {}
